AWSTemplateFormatVersion: 2010-09-09
Description: AppSync Demo Master Stack
Outputs:
  UiStackId:
    Value: !Ref UiStack
  UiBucketName:
    Value: !GetAtt UiStack.Outputs.SiteBucketId
  UiUrl:
    Value: !GetAtt UiStack.Outputs.SiteBucketWebsiteUrl
  StorageStackId:
    Value: !Ref StorageStack
  ApiStackId:
    Value: !Ref ApiStack
  ApiUrl:
    Value: !GetAtt ApiStack.Outputs.GraphqlApiUrl
Resources:
  UiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ui.yml
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./storage.yml
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
    Properties:
      Parameters:
        DataAccessPolicyArn: !GetAtt StorageStack.Outputs.DataAccessPolicyArn
        EventsTableName: !GetAtt StorageStack.Outputs.EventsTableName
        CommentsTableName: !GetAtt StorageStack.Outputs.CommentsTableName
      TemplateURL: ./api.yml
