AWSTemplateFormatVersion: 2010-09-09
Description: AppSync Demo Storage
Outputs:
  DataAccessPolicyArn:
    Value: !Ref DataAccessPolicy
  EventsTableName:
    Value: !Ref EventsTable
  CommentsTableName:
    Value: !Ref CommentsTable
Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Events
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CommentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Comments
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: commentId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: commentId
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: comments-by-eventId-createdAt
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  DataAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Read/write access to AppSync Demo tables
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Join [ '', [ !GetAtt EventsTable.Arn, '*' ] ]
              - !Join [ '', [ !GetAtt CommentsTable.Arn, '*' ] ]
