AWSTemplateFormatVersion: 2010-09-09
Description: AppSync Demo UI
Outputs:
  SiteBucketId:
    Value: !Ref SiteBucket
  SiteBucketWebsiteUrl:
    Value: !GetAtt SiteBucket.WebsiteURL
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
